import fs from 'node:fs';
import vm from 'node:vm';
import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
import ts from 'typescript';
const require=createRequire(import.meta.url);
const source=ts.transpileModule(fs.readFileSync('src/app/api/support/route.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
let calls=[];
let dbResult={data:{id:'test-id'},error:null};
let deliveries=[];
let deliveryOk=true;
let invalidated=false;
const sandbox={exports:{},Response,URL,Buffer,AbortSignal,process:{env:{VERCEL:'1',SUPABASE_SERVICE_ROLE_KEY:'test-secret',RESEND_API_KEY:'mail-test',RESEND_FROM_EMAIL:'support@example.test'}},fetch:async(url,options)=>{deliveries.push(JSON.parse(options.body));return {ok:deliveryOk};},require:name=>name==='@/lib/supabase-admin'?{createSupabaseAdminClient:()=>({rpc:async(name,args)=>{calls.push({name,args});return dbResult;},from:()=>({update:()=>({eq:async()=>{invalidated=true;}})})})}:require(name)};
vm.runInNewContext(source,sandbox);
const valid={action:'request',email:' Test@Example.com ',subject:'Ajuda',description:'Preciso de ajuda com o site.'};
const request=(body,headers={})=>new Request('https://example.test/api/support',{method:'POST',headers:{origin:'https://example.test','content-type':'application/json','x-vercel-forwarded-for':'192.0.2.1',...headers},body:typeof body==='string'?body:JSON.stringify(body)});
assert.equal((await sandbox.exports.POST(request(valid,{origin:'https://evil.test'}))).status,403);
assert.equal((await sandbox.exports.POST(request({...valid,email:'invalid'}))).status,400);
assert.equal((await sandbox.exports.POST(request({...valid,description:'x'.repeat(5001)}))).status,400);
assert.equal((await sandbox.exports.POST(request('x'.repeat(32769)))).status,413);
assert.equal(calls.length,0);
assert.equal((await sandbox.exports.POST(request({...valid,action:undefined}))).status,400,'Legacy direct submission is rejected');
const response=await sandbox.exports.POST(request(valid));
assert.equal(response.status,202);
const result=await response.json();
assert.ok(result.challengeId);
assert.ok(!('code' in result));
assert.equal(calls[0].name,'request_support_code');
assert.equal(calls[0].args.p_email,'test@example.com');
assert.equal(calls[0].args.p_origin_hash.length,64);
assert.ok(!JSON.stringify(calls[0]).includes('192.0.2.1'));
const code=deliveries[0].text.match(/\b\d{6}\b/)[0];
assert.equal(calls[0].args.p_code_hash,require('node:crypto').createHmac('sha256','test-secret').update(`support-code:${result.challengeId}:${code}`).digest('hex'));
assert.equal((await sandbox.exports.POST(request({action:'verify',id:result.challengeId,code}))).status,201);
assert.equal(calls.at(-1).name,'confirm_support_code');
assert.deepEqual(Object.keys(calls.at(-1).args).sort(),['p_code_hash','p_id']);
dbResult={data:{error:'locked_code'},error:null};
assert.equal((await sandbox.exports.POST(request({action:'verify',id:result.challengeId,code}))).status,429);
dbResult={data:{error:'rate_limit'},error:null};
assert.equal((await sandbox.exports.POST(request(valid))).status,429);
assert.equal(deliveries.length,1,'Rate-limited requests do not send email');
dbResult={data:{id:'test-id'},error:null};
deliveryOk=false;
assert.equal((await sandbox.exports.POST(request(valid))).status,503);
assert.ok(invalidated,'Provider rejection invalidates the pending code');
dbResult={data:null,error:{message:'database unavailable'}};
assert.equal((await sandbox.exports.POST(request(valid))).status,503);
console.log('PASS: origin and payload limits, legacy bypass rejected, code only in email, hashed code/origin, request/verify split, limits, delivery and persistence errors');
