-- Ownership and database-enforced moderator permissions for guide/flow content.
ALTER TABLE public.guides
  ADD COLUMN IF NOT EXISTS created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL;

-- Os guias anteriores ao rastreamento de autoria foram publicados pela conta
-- editorial PqEstudar. author_name não identifica a conta autenticada e não
-- deve ser usado para inferir propriedade.
UPDATE public.guides
SET created_by = (
  SELECT id
  FROM auth.users
  WHERE lower(email) = 'pqestudar.suporte@gmail.com'
  LIMIT 1
)
WHERE created_by IS NULL
  AND EXISTS (
    SELECT 1
    FROM auth.users
    WHERE lower(email) = 'pqestudar.suporte@gmail.com'
  );

CREATE INDEX IF NOT EXISTS guides_created_by_idx ON public.guides(created_by);

CREATE TABLE IF NOT EXISTS public.guide_audit_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guide_id uuid,
  actor_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  action text NOT NULL CHECK (action IN ('create', 'update', 'delete')),
  old_data jsonb,
  new_data jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.guide_audit_log ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.set_guide_owner()
RETURNS trigger
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    NEW.created_by := auth.uid();
  ELSIF NOT public.has_role(auth.uid(), 'admin'::public.app_role)
        AND NOT public.has_role(auth.uid(), 'developer'::public.app_role) THEN
    NEW.created_by := OLD.created_by;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS set_guide_owner_trigger ON public.guides;
CREATE TRIGGER set_guide_owner_trigger
BEFORE INSERT OR UPDATE ON public.guides
FOR EACH ROW EXECUTE FUNCTION public.set_guide_owner();

CREATE OR REPLACE FUNCTION public.audit_guide_changes()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.guide_audit_log (guide_id, actor_id, action, old_data, new_data)
  VALUES (
    COALESCE(NEW.id, OLD.id),
    auth.uid(),
    CASE TG_OP WHEN 'INSERT' THEN 'create' WHEN 'UPDATE' THEN 'update' ELSE 'delete' END,
    CASE WHEN TG_OP IN ('UPDATE', 'DELETE') THEN to_jsonb(OLD) END,
    CASE WHEN TG_OP IN ('INSERT', 'UPDATE') THEN to_jsonb(NEW) END
  );
  RETURN COALESCE(NEW, OLD);
END;
$$;

DROP TRIGGER IF EXISTS audit_guide_changes_trigger ON public.guides;
CREATE TRIGGER audit_guide_changes_trigger
AFTER INSERT OR UPDATE OR DELETE ON public.guides
FOR EACH ROW EXECUTE FUNCTION public.audit_guide_changes();

-- Replace existing guide policies so no older broad authenticated policy can
-- accidentally grant moderators write access to somebody else's content.
DO $$
DECLARE policy_row record;
BEGIN
  FOR policy_row IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'guides'
  LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.guides', policy_row.policyname);
  END LOOP;
END $$;

ALTER TABLE public.guides ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public reads published guides" ON public.guides
FOR SELECT USING (
  is_published
  OR public.has_role(auth.uid(), 'admin'::public.app_role)
  OR public.has_role(auth.uid(), 'developer'::public.app_role)
  OR public.has_role(auth.uid(), 'moderator'::public.app_role)
);

CREATE POLICY "Admins and moderators create guides" ON public.guides
FOR INSERT TO authenticated WITH CHECK (
  public.has_role(auth.uid(), 'admin'::public.app_role)
  OR public.has_role(auth.uid(), 'developer'::public.app_role)
  OR (public.has_role(auth.uid(), 'moderator'::public.app_role) AND created_by = auth.uid())
);

CREATE POLICY "Admins or owners update guides" ON public.guides
FOR UPDATE TO authenticated
USING (
  public.has_role(auth.uid(), 'admin'::public.app_role)
  OR public.has_role(auth.uid(), 'developer'::public.app_role)
  OR (public.has_role(auth.uid(), 'moderator'::public.app_role) AND created_by = auth.uid())
)
WITH CHECK (
  public.has_role(auth.uid(), 'admin'::public.app_role)
  OR public.has_role(auth.uid(), 'developer'::public.app_role)
  OR (public.has_role(auth.uid(), 'moderator'::public.app_role) AND created_by = auth.uid())
);

CREATE POLICY "Admins or owners delete guides" ON public.guides
FOR DELETE TO authenticated USING (
  public.has_role(auth.uid(), 'admin'::public.app_role)
  OR public.has_role(auth.uid(), 'developer'::public.app_role)
  OR (public.has_role(auth.uid(), 'moderator'::public.app_role) AND created_by = auth.uid())
);

CREATE POLICY "Admins read guide audit" ON public.guide_audit_log
FOR SELECT TO authenticated USING (
  public.has_role(auth.uid(), 'admin'::public.app_role)
  OR public.has_role(auth.uid(), 'developer'::public.app_role)
);

CREATE OR REPLACE FUNCTION public.moderator_authors()
RETURNS TABLE(user_id uuid, display_name text, email text)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, auth
AS $$
  SELECT u.id,
         COALESCE(NULLIF(u.raw_user_meta_data->>'full_name', ''), split_part(u.email, '@', 1)),
         u.email
  FROM auth.users u
  JOIN public.user_roles ur ON ur.user_id = u.id
  WHERE ur.role = 'moderator'::public.app_role
    AND (
      u.id = auth.uid()
      OR public.has_role(auth.uid(), 'admin'::public.app_role)
      OR public.has_role(auth.uid(), 'moderator'::public.app_role)
    )
  ORDER BY 2;
$$;

REVOKE ALL ON FUNCTION public.moderator_authors() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.moderator_authors() TO authenticated;
