-- Block 4 / Part B2 (3 of 7): audited TSEE eligibility rules.
-- Official sources checked 2026-09-04. Household-derived income is supporting
-- because the profile household may differ from the official registered family.

WITH benefit AS (SELECT id FROM public.premium_items WHERE slug = 'tarifa-social-de-energia-eletrica'), rules (
  benefit_id, rule_key, route_key, applies_to_routes, criterion_key, operator, expected_value,
  group_key, group_operator, importance, match_message, unknown_message, mismatch_message,
  source_url, verified_at, effective_from, effective_to, reference_period, rule_version, sort_order, is_active
) AS (
  SELECT id,'tsee-low-cadunico','cadunico_low_income',NULL::text[],'cadunico_status','equals','"yes"'::jsonb,'tsee-low-core','and','required','O perfil informa inscrição no CadÚnico.','Falta informar a situação no CadÚnico para avaliar esta forma de acesso.','Esta forma de acesso exige inscrição no CadÚnico.','https://www.gov.br/aneel/pt-br/assuntos/tarifas/tarifa-social',DATE '2026-09-04',DATE '2026-01-01',DATE '2026-12-31','salario_minimo_2026',1,10,true FROM benefit
  UNION ALL SELECT id,'tsee-low-income-estimate','cadunico_low_income',NULL::text[],'per_capita_income','less_than_or_equal','810.50'::jsonb,'tsee-low-income','and','supporting','A estimativa informada está dentro de meio salário mínimo por pessoa.','Não há dados suficientes para estimar a renda por pessoa.','A estimativa doméstica supera meio salário mínimo por pessoa, mas o cálculo oficial da família ainda precisa ser confirmado.','https://www.gov.br/aneel/pt-br/assuntos/tarifas/tarifa-social',DATE '2026-09-04',DATE '2026-01-01',DATE '2026-12-31','salario_minimo_2026',1,20,true FROM benefit
  UNION ALL SELECT id,'tsee-medical-cadunico','medical_equipment',NULL::text[],'cadunico_status','equals','"yes"'::jsonb,'tsee-medical-core','and','required','O perfil informa inscrição no CadÚnico.','Falta informar a situação no CadÚnico para avaliar a rota de equipamento médico.','A rota de equipamento médico exige inscrição no CadÚnico.','https://www.gov.br/aneel/pt-br/assuntos/tarifas/tarifa-social',DATE '2026-09-04',DATE '2026-01-01',DATE '2026-12-31','salario_minimo_2026',1,30,true FROM benefit
  UNION ALL SELECT id,'tsee-medical-income-estimate','medical_equipment',NULL::text[],'household_monthly_income','less_than_or_equal','4863.00'::jsonb,'tsee-medical-income','and','supporting','A renda doméstica informada está dentro de três salários mínimos.','Falta informar a renda para estimar esta forma de acesso.','A renda doméstica informada supera três salários mínimos, mas a composição familiar oficial ainda precisa ser confirmada.','https://www.gov.br/aneel/pt-br/assuntos/tarifas/tarifa-social',DATE '2026-09-04',DATE '2026-01-01',DATE '2026-12-31','salario_minimo_2026',1,40,true FROM benefit
  UNION ALL SELECT id,'tsee-medical-disability-signal','medical_equipment',NULL::text[],'disability','is_true','true'::jsonb,'tsee-medical-health-condition','or','required','Foi declarada deficiência, um sinal compatível com esta rota.','Não foi informado se há deficiência; outra condição de saúde também pode tornar esta rota aplicável.','Não foi declarada deficiência, mas uma doença não representada no perfil ainda pode tornar esta rota aplicável.','https://www.gov.br/aneel/pt-br/assuntos/tarifas/tarifa-social',DATE '2026-09-04',DATE '2026-01-01',DATE '2026-12-31','requisitos_tsee_2026',1,50,true FROM benefit
  UNION ALL SELECT id,'tsee-bpc-age-signal','bpc_recipient',NULL::text[],'age','greater_than_or_equal','65'::jsonb,'tsee-bpc-person','or','required','A idade informada é compatível com a rota de beneficiário do BPC.','Falta informar a idade para avaliar um dos sinais desta rota.','A idade informada não atende ao sinal de pessoa idosa, mas deficiência ainda pode tornar a rota aplicável.','https://www.gov.br/aneel/pt-br/assuntos/tarifas/tarifa-social',DATE '2026-09-04',DATE '2026-01-01',DATE '2026-12-31','requisitos_tsee_2026',1,60,true FROM benefit
  UNION ALL SELECT id,'tsee-bpc-disability-signal','bpc_recipient',NULL::text[],'disability','is_true','true'::jsonb,'tsee-bpc-person','or','required','Foi declarada deficiência, um sinal compatível com a rota de beneficiário do BPC.','Falta informar se há deficiência para avaliar o segundo sinal desta rota.','Não foi declarada deficiência.','https://www.gov.br/aneel/pt-br/assuntos/tarifas/tarifa-social',DATE '2026-09-04',DATE '2026-01-01',DATE '2026-12-31','requisitos_tsee_2026',1,70,true FROM benefit
)
INSERT INTO public.benefit_eligibility_criteria (benefit_id,rule_key,route_key,applies_to_routes,criterion_key,operator,expected_value,group_key,group_operator,importance,match_message,unknown_message,mismatch_message,source_url,verified_at,effective_from,effective_to,reference_period,rule_version,sort_order,is_active)
SELECT * FROM rules ON CONFLICT (benefit_id,rule_key,rule_version) DO UPDATE SET route_key=EXCLUDED.route_key,applies_to_routes=EXCLUDED.applies_to_routes,criterion_key=EXCLUDED.criterion_key,operator=EXCLUDED.operator,expected_value=EXCLUDED.expected_value,group_key=EXCLUDED.group_key,group_operator=EXCLUDED.group_operator,importance=EXCLUDED.importance,match_message=EXCLUDED.match_message,unknown_message=EXCLUDED.unknown_message,mismatch_message=EXCLUDED.mismatch_message,source_url=EXCLUDED.source_url,verified_at=EXCLUDED.verified_at,effective_from=EXCLUDED.effective_from,effective_to=EXCLUDED.effective_to,reference_period=EXCLUDED.reference_period,sort_order=EXCLUDED.sort_order,is_active=EXCLUDED.is_active;

WITH benefit AS (SELECT id FROM public.premium_items WHERE slug='tarifa-social-de-energia-eletrica'), checks (benefit_id,route_key,applies_to_routes,verification_key,group_key,group_operator,message,sort_order) AS (
 SELECT id,'cadunico_low_income',NULL::text[],'tsee-low-official-income',NULL::text,NULL::text,'É necessário confirmar a renda e a composição da família registradas oficialmente.',20 FROM benefit
 UNION ALL SELECT id,'cadunico_low_income',NULL::text[],'tsee-low-cadunico-current',NULL,NULL,'É necessário confirmar que o CadÚnico foi atualizado nos últimos dois anos.',30 FROM benefit
 UNION ALL SELECT id,'medical_equipment',NULL::text[],'tsee-medical-disease','tsee-medical-health-condition','or','Uma doença ou condição de saúde não coletada pelo perfil pode tornar esta rota aplicável.',40 FROM benefit
 UNION ALL SELECT id,'medical_equipment',NULL::text[],'tsee-medical-official-income',NULL,NULL,'É necessário confirmar a renda familiar total no cadastro oficial.',50 FROM benefit
 UNION ALL SELECT id,'medical_equipment',NULL::text[],'tsee-medical-continuous-equipment',NULL,NULL,'É necessário confirmar que o tratamento exige uso continuado de equipamento elétrico.',60 FROM benefit
 UNION ALL SELECT id,'medical_equipment',NULL::text[],'tsee-medical-documentation',NULL,NULL,'É necessário apresentar relatório e atestado médico à distribuidora.',70 FROM benefit
 UNION ALL SELECT id,'medical_equipment',NULL::text[],'tsee-medical-cadunico-current',NULL,NULL,'É necessário confirmar que o CadÚnico foi atualizado nos últimos dois anos.',80 FROM benefit
 UNION ALL SELECT id,'bpc_recipient',NULL::text[],'tsee-effective-bpc-recipient',NULL,NULL,'É necessário confirmar o recebimento efetivo do BPC por pessoa idosa ou com deficiência.',90 FROM benefit
 UNION ALL SELECT id,'common',ARRAY['cadunico_low_income','medical_equipment','bpc_recipient'],'tsee-residential-unit',NULL,NULL,'É necessário confirmar que a unidade consumidora é residencial.',100 FROM benefit
 UNION ALL SELECT id,'common',ARRAY['cadunico_low_income','medical_equipment','bpc_recipient'],'tsee-single-unit-family',NULL,NULL,'É necessário confirmar que esta é a única unidade consumidora beneficiada pela família.',110 FROM benefit
 UNION ALL SELECT id,'common',ARRAY['cadunico_low_income','medical_equipment','bpc_recipient'],'tsee-address-compatible',NULL,NULL,'É necessário confirmar que o endereço cadastrado pertence à área atendida pela distribuidora.',120 FROM benefit
)
INSERT INTO public.benefit_eligibility_verifications (benefit_id,route_key,applies_to_routes,verification_key,group_key,group_operator,message,source_url,verified_at,effective_from,effective_to,reference_period,rule_version,sort_order,is_active)
SELECT benefit_id,route_key,applies_to_routes,verification_key,group_key,group_operator,message,'https://www.gov.br/aneel/pt-br/assuntos/tarifas/tarifa-social',DATE '2026-09-04',DATE '2026-01-01',DATE '2026-12-31','requisitos_tsee_2026',1,sort_order,true FROM checks
ON CONFLICT (benefit_id,verification_key,route_key,rule_version) DO UPDATE SET applies_to_routes=EXCLUDED.applies_to_routes,group_key=EXCLUDED.group_key,group_operator=EXCLUDED.group_operator,message=EXCLUDED.message,source_url=EXCLUDED.source_url,verified_at=EXCLUDED.verified_at,effective_from=EXCLUDED.effective_from,effective_to=EXCLUDED.effective_to,reference_period=EXCLUDED.reference_period,sort_order=EXCLUDED.sort_order,is_active=EXCLUDED.is_active;

NOTIFY pgrst, 'reload schema';
